Hello!
===
### Как настроить совместную работу

1. Создать аккаунт на GitHub.com
2. Создать локальный репозиторий
3. “Подружить” ваш локальный и удалённый репозитории.GitHub при создании нового репозитория подскажет, как это можно сделать
4. Отправить (push) ваш локальный репозиторий в удалённый (на GitHub), при этом, возможно,  
вам нужно будет авторизоваться на удалённом репозитории
5. Провести изменения “с другого компьютера”
6. Выкачать (pull) актуальное состояние из удалённого репозитория.

Вы пишете код для жизни? Затем изучите Git и изучите его хорошо. Инструмент, первоначально созданный Линусом Торвальдсом — да, создателем ядра Linux — стал стандартом де-факто, когда дело доходит до решений для управления версиями. Чтобы помочь вам в процессе обучения, мы рассмотрели распространенные ошибки Git и объяснили, как из них выбраться.

Ошибка "Удаленный источник уже существует": почему это происходит?
Представьте это: вы следуете руководству по Git, которое вы нашли в Интернете. Пока все работает нормально. Затем вы увидите строку, похожую на следующую:

### git remote add origin <SOME-URL>/<SOME-REPOSITORY-NAME>.git

После попытки выполнить приведенную выше команду вы получаете печально известное сообщение об ошибке:

__fatal: remote origin already exists.__

Понять это сообщение на самом деле легко. В отличие от централизованных VCS, у Git нет центрального сервера. В Git у вас может быть то, что мы называем удаленными репозиториями, или просто удаленными. Удаленные хранилища представляют собой хранилища, к которым у вас может быть доступ на чтение и / или запись. Обычно они находятся на компьютерах, отличных от ваших, и вы получаете к ним доступ через SSH или HTTP. Имейте в виду, что, несмотря на название, пульты не обязательно расположены на удаленных машинах: несмотря на то, что это звучит как оксюморон, локальные пульты вполне возможны.


У удаленных устройств есть имена для их идентификации, и у вас может быть столько удаленных устройств в репозитории, сколько вам нужно или хотите. Однако у вас не может быть двух пультов с одинаковым именем. Поэтому, если вы попытаетесь добавить пульт с тем же именем, что и у уже существующего пульта, бум! Фатальная ошибка.

Если вы хотите быть действительно уверены, что удаленный вызываемый источник действительно существует, вы можете легко проверить это, выполнив следующую команду:

__git remote__
  
## __Устранение ошибки "Удаленный источник уже существует" четырьмя различными способами__
===

Объяснив, почему появляется сообщение об ошибке, мы теперь рассмотрим некоторые из нескольких потенциальных решений, которые вы можете использовать для решения проблемы. Имейте в виду, что решение, которое вы будете использовать, будет зависеть от вашей конкретной ситуации, поскольку существует несколько различных сценариев, которые могут вызвать возникновение этой проблемы.


Добавили дополнительный текст в строку 39
